package analyzer.cfg.reachDefinition;

import java.util.List;

import analyzer.cfg.predicate.INodePredicateChainRecorder;

/**
 * @author Zhou Xiaocong
 * @since 2018年7月14日
 * @version 1.0
 *
 */
public interface IReachConditionDefinitionRecorder extends INodePredicateChainRecorder, IReachDefinitionRecorder {
	
	/**
	 * Add a generated definition and its value (reference).
	 * Note: a generated definition in a node also kills all definition defined in the precede nodes 
	 */
	public void addGeneratedConditionDefinition(GeneratedConditionDefinitionRecorder definition);

	/**
	 * Add a definition to the current node. All added definition can reach this node. 
	 * In fact, those definitions include generated definitions in this node and all definitions
	 * which reach the precede nodes and not killed by this node. 
	 */
	public boolean addReachingConditionDefinition(ConditionDefinitionRecorder definition);
	
	/**
	 * Add a definition to the reaching definition list of the program point in (i.e. before) this node. 
	 */
	public boolean addInReachingConditionDefinition(ConditionDefinitionRecorder definition);

	/**
	 * Get the definition list of the program point in (i.e. before) this node.
	 */
	public List<ConditionDefinitionRecorder> getInReachingConditionDefinitionList();
	
	/**
	 * Get all defined names reach this node
	 */
	public List<ConditionDefinitionRecorder> getReachingConditionDefinitionList();
	
	/**
	 * Get all defined names generated by this node
	 * Note: we can also get all killed names by this node from its generated names
	 */
	public List<GeneratedConditionDefinitionRecorder> getGeneratedConditionDefinitionList();

}
